# This workflow builds and tests PRs

name: PR build & test

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "lyncs*/__init__.py"

jobs:
  build-n-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        py-version:
          - 3.x
        mpi:
          - openmpi
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install MPI (${{ matrix.mpi }})
        run: bash .bash/install-${{ matrix.mpi }}.sh

      - name: Set up Python ${{ matrix.py-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.py-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lyncs_setuptools

      - name: Upload if not up to date
        id: check-version
        continue-on-error: true
        run: 
          pip install --extra-index-url https://test.pypi.org/simple/ lyncs_io==$(lyncs_setuptools version)

      - name: Install from source
        if: ${{ steps.check-version.conclusion == 'failure' }}
        run: |
          pip install -e .[all]

      - name: Run tests
        if: ${{ steps.check-version.conclusion == 'failure' }}
        run: |
          pytest -v

      - name: Upload if not up to date
        if: ${{ steps.check-version.conclusion == 'failure' }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.test_pypi_password }}
        run: |
          pip uninstall -y lyncs_io
          pip install twine
          python setup.py sdist
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
          # waiting for pip to update the index
          sleep 60

  clean-run:
    if: ${{ steps.check-version.conclusion == 'failure' }}
    needs: build-n-publish
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        py-version:
          - 3.6
          - 3.7
          - 3.8
        mpi:
          - openmpi
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install via pip
        run: |
          pip install --extra-index-url https://test.pypi.org/simple/ lyncs_io[all]

      - name: Run tests
        run: |
          pytest -v --import-mode=importlib
