# This workflow runs test

name: tests

on:
  pull_request:
    branches:
      - "main"
      - "develop"
  push:
    branches:
      - "main"
      - "develop"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.x
        mpi:
          - openmpi
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python ${{ matrix.py-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py-version }}

       - name: Install OpenMPI Parallel HDF5
        run: bash .bash/install-hdf5.sh

      - name: Install h5py
        run: |
          CC=mpicc HDF5_MPI="ON" HDF5_DIR="/usr/lib/x86_64-linux-gnu/hdf5/openmpi" pip install --no-binary=h5py h5py
      
          - name: Example using h5py
        run: |
          mpirun -n 4 --oversubscribe python .bash/ph5py-example.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lyncs_setuptools

      - name: Install via pip
        run: |
          pip install -e .[all]

      - name: Run serial tests
        run: |
          coverage run --rcfile=setup.cfg -m pytest test/serial

      - name: Run MPI tests (procs=2, 4, 7, 12)
        run: |
          PROCS=(2 4 7 12)
          for proc in "${PROCS[@]}"
          do
            echo "::group::Run MPI tests (procs=$proc)"
            mpirun -n $proc coverage run --rcfile=setup.cfg -m pytest test/MPI --with-mpi
            echo "::endgroup::"
          done

      - name: Run Dask tests
        run: |
          coverage run --rcfile=setup.cfg -m pytest test/Dask

      - name: Coverage report
        run: |
          coverage combine
          coverage report

      - name: Upload Coverage report
        if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && matrix.py-version == '3.x' }}
        run: |
          coverage xml
          export CODECOV_TOKEN="${{ secrets.CODECOV_TOKEN }}"
          bash <(curl -s https://codecov.io/bash) -f ./coverage.xml -n $(lyncs_setuptools name)
