# This workflow builds and runs test

name: tests

on:
  pull_request:
    branches:
      - "main"
      - "develop"
    paths-ignore:
      - "docs/**"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py-version:
          - 3.6
          - 3.7
          - 3.8
        mpi:
          - openmpi
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install MPI (${{ matrix.mpi }})
        run: bash .bash/install-${{ matrix.mpi }}.sh

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install via pip
        run: |
          sudo pip install -e .[all]

      - name: Run serial tests
        run: |
          pytest -v

      - name: Run parallel tests (procs=2)
        run: |
          mpirun -n 2 --oversubscribe python -m pytest test/parallel_tests/ --with-mpi

      - name: Run parallel tests (procs=4)
        run: |
          mpirun -n 4 --oversubscribe python -m pytest test/parallel_tests/ --with-mpi

      - name: Run parallel tests (procs=7)
        run: |
          mpirun -n 7 --oversubscribe python -m pytest test/parallel_tests/ --with-mpi

      - name: Run parallel tests (procs=12)
        run: |
          mpirun -n 12 --oversubscribe python -m pytest test/parallel_tests/ --with-mpi

      - name: Run tests with coverage
        run: |
          coverage run --rcfile=setup.cfg -m pytest
          # Individual coverage is generated per core
          mpiexec -n 2 --oversubscribe coverage run --rcfile=setup.cfg -m mpi4py -m pytest test/parallel_tests/ --with-mpi
          # Combine serial and parallel coverage reports
          coverage combine
          coverage xml
          export CODECOV_TOKEN="${{ secrets.CODECOV_TOKEN }}"
          bash <(curl -s https://codecov.io/bash) -f ./coverage.xml -n lyncs_io
