# This workflow builds and runs test

name: tests

on:
  pull_request:
    branches:
      - "main"
      - "develop"
    paths-ignore:
      - "docs/**"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py-version:
          - 3.6
          - 3.7
          - 3.8
        mpi:
          - openmpi
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install MPI (${{ matrix.mpi }})
        run: bash .bash/install-${{ matrix.mpi }}.sh

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install via pip
        run: |
          sudo pip install -e .[all]

      - name: Run serial tests
        run: |
          pytest -v

      - name: Run parallel tests (procs=2, 4, 7, 12)
        run: |
          PROCS=(2 4 7 12)
          for proc in "${PROCS[@]}"
          do
            mpirun -n $proc --oversubscribe python -m pytest test/parallel_tests/ --with-mpi
          done
